"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TrunkInstance:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _TrunkInstanceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TrunkInstance.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ALL: _TrunkInstance.ValueType  # 0
    FRONT: _TrunkInstance.ValueType  # 1
    REAR: _TrunkInstance.ValueType  # 2
class TrunkInstance(_TrunkInstance, metaclass=_TrunkInstanceEnumTypeWrapper):
    pass

ALL: TrunkInstance.ValueType  # 0
FRONT: TrunkInstance.ValueType  # 1
REAR: TrunkInstance.ValueType  # 2
global___TrunkInstance = TrunkInstance


class _LockState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LockStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LockState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCKED: _LockState.ValueType  # 0
    UNLOCKED: _LockState.ValueType  # 1
class LockState(_LockState, metaclass=_LockStateEnumTypeWrapper):
    pass

LOCKED: LockState.ValueType  # 0
UNLOCKED: LockState.ValueType  # 1
global___LockState = LockState


class SetLockStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTANCE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    instance: global___TrunkInstance.ValueType
    state: global___LockState.ValueType
    def __init__(self,
        *,
        instance: global___TrunkInstance.ValueType = ...,
        state: global___LockState.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["instance",b"instance","state",b"state"]) -> None: ...
global___SetLockStateRequest = SetLockStateRequest

class SetLockStateReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___SetLockStateReply = SetLockStateReply

class OpenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: global___TrunkInstance.ValueType
    def __init__(self,
        *,
        instance: global___TrunkInstance.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["instance",b"instance"]) -> None: ...
global___OpenRequest = OpenRequest

class OpenReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___OpenReply = OpenReply

class CloseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: global___TrunkInstance.ValueType
    def __init__(self,
        *,
        instance: global___TrunkInstance.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["instance",b"instance"]) -> None: ...
global___CloseRequest = CloseRequest

class CloseReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___CloseReply = CloseReply
